const key = {
  SET_AUTH: "SET_AUTH",
  SET_CONFIG: "SET_CONFIG",
  LOG_OUT: "LOG_OUT",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  GET_USER_PROFILE: "GET_USER_PROFILE",
  FIRST_LOGIN: "FIRST_LOGIN",
  ONE_LOGIN: "ONE_LOGIN",
  TWO_LOGIN: "TWO_LOGIN",
  SET_LOGIN: "SET_LOGIN",
  CALLING: "CALLING",
  LOADING: "LOADING"
}

export default key
