import React from "react"
import OTPInput from "react-otp-input"
import styles from "./styles.module.css"
import { strategieCode } from "../../lib/const"

export default function InputOtp({
  value,
  onChange,
  error,
  onResend,
  step,
  strategie,
  firstSignIn
}) {
  return (
    <div className="">
      <div className={styles.ox_box_header}>
        {step === 2 && strategie === strategieCode.EMAIL_CODE && (
          <div>
            <div className={styles.ox_name_title}>Check your email</div>
            <div>
              <div className={styles.ox_info_signin}>to continue to {firstSignIn?.appName}</div>
              <div> {firstSignIn?.email}</div>
            </div>
          </div>
        )}
        {step === 2 && strategie === strategieCode.EMAIL_LINK && "Verify your email"}
        {step === 3 && <div className={styles.ox_name_title}>Two-step verification</div>}
      </div>
      <div className={styles.ox_sub_code}>
        {step === 3 &&
          strategie === strategieCode.EMAIL_CODE &&
          "Enter the verification code sent to your email"}
        {step === 3 &&
          "To continue, please enter the verification code generated by your authenticator app"}
      </div>
      <OTPInput
        containerStyle={styles.ox_otp_container}
        value={value}
        onChange={onChange}
        numInputs={6}
        inputStyle={error ? styles.ox_input_error : styles.ox_input}
        renderSeparator={<div className={styles.otp_space}></div>}
        renderInput={(props) => <input {...props} />}
      />
      <div className={styles.ox_error}>{error && error}</div>
      <div className={styles.ox_box_link}>
        <button className={styles.ox_link} onClick={onResend}>
          Didn't receive a code? Resend
        </button>
      </div>
    </div>
  )
}
